### ISSUE TITLE
Issues in screenfull

### ISSUE THREAD

**Issue by reberinformatik** [jpilfold/ngx-image-viewer#29]
Screenfull has fixed some issues in the latest version. Would it be possible to update the package?

Related: #23

**Comment by troglodito** [comment]
We also still get this error mentioned in #23.

Updating screenfull.js version to at least [v4.0.1](https://github.com/sindresorhus/screenfull.js/releases/tag/v4.0.1), where the problem has been fixed, will automatically solve the problem several users were reporting in the issue mentioned above. 

Manually editing the sreenfull.js - as e.g. described in  [this comment](https://github.com/jpilfold/ngx-image-viewer/issues/23#issuecomment-451545287) is not a real solution when you have integrated ngx-image-viewer in your project and call `npm install `for a build.

Could you please update the package and publish a new release?

**Comment by ebitauld** [comment]
I implemented this library in angular 7.
Updating screenfull.js version to at least v4.0.1 does not solve the issue for me.
I tried npm install screenfull@4.0.1, but I still get the same error :
"Uncaught (in promise) TypeError: Document not active"

**Comment by troglodito** [comment]
@ebitauld : I understand that you did an own implementation of this library or a fork, right?
Then calling npm install on screenfull won't do the trick, instead you have to open package.json in your project, update the dependency to screenful.js (in ngx-image-viewer 1.0.13 it's currently "^3.3.2", which was actually resolved in package-lock.json to version 3.3.2 and then call `npm install` on your project - this is what we kindly ask @jpilfold to do.

**Comment by pgadirajuot** [comment]
Hey guys,

I think updating the screenfull.js package doesn't seem to fix the issue. The issue is in lines. 

[` } else if (screenfull.enabled) {
            screenfull.exit();
  }`](https://github.com/jpilfold/ngx-image-viewer/blob/6ccf522e9386ee6f97a09b7d5c768b31d16dd07d/src/app/image-viewer/fullscreen.directive.ts#L17)

`screenfull.enabled` is true even on the initial load and calling the `exit` method when there's no fullscreen hence we're facing the issues.

**Comment by udham-singh** [comment]
Anyone having this issue can refer to [this](https://www.npmjs.com/package/@udhsin/ngx-image-viewer) fork which resolves it. Thanks.
